version: '3'

services:
  activo:
    build: ./microservice
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/microservicio
  monolitico:
    build: ./monolitico
    depends_on:
      - mongo
    environment:
      - DB_MONGO=mongodb://mongo:27017/monolitico
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - activo
      - monolitico